#!/bin/bash

#PBS -N classifier_all
#PBS -l select=1:ncpus=4:mem=16gb:ngpus=1:gpu_model=k40:interconnect=fdr,walltime=24:00:00
#PBS -j oe

# GPU node command request:
#   -l select=1:ncpus=4:mem=16gb:ngpus=1:gpu_model=p100:interconnect=fdr,walltime=2:00:00

cd $PBS_O_WORKDIR

module load anaconda3/5.1.0-gcc/8.3.1
source activate myenv

for filename in data/*.csv; do
    echo testing $filename
    python lstm.py --file_name $filename --threshold 2 --test_split 0.3 --epochs 100
done

